[info]
# Station name
station_name = "Tower Radio"
# Station website
station_website = "towerradio.co.uk"
# License email
license_email = "harry@towerradio.co.uk"

# Location for weather API
[location]
lat = "52.7000000"
lon = "-0.1000000"

[server]
# Web server host IP
host = "0.0.0.0"
# Web server port
port = 25543

[azuracast]
# AzuraCast Dashboard URL
radio_url = "https://manage.towerradio.co.uk"
# AzuraCast API Key
api_key = ""
# AzuraCast Station ID
station_id = 1

[other]
debug = false